entries:
- src_topic: slimmemeter
  dst_name: slimmemeter
  throttle_ms: 1000
  type: "json"
  fields:
  - src_path: power_delivered
    dst_name: power_delivered_kw
  - src_path: power_failures
  - src_path: meterreadings.0.to
    dst_name: meterreading_low_kwh
  - src_path: meterreadings.1.to
    dst_name: meterreading_high_kwh
  - src_path: lines.0.active_power_plus
    dst_name: l0_power_kw
  - src_path: lines.1.active_power_plus
    dst_name: l1_power_kw
  - src_path: lines.2.active_power_plus
    dst_name: l2_power_kw
  - src_path: slaves.0.meter_reading.1
    dst_name: gas_m3